### ISSUE TITLE
v4.5 standard pcb layers 2 or 4?

### ISSUE THREAD

**Issue by chuckmerja** [AgHardware/Boards#2]
im trying to order standard board v 4.5.  the install advisor (https://github.com/AgHardware/Boards/wiki/AIO-Board-flavours) says JLC default is 2 layer, but when upload gerber it should detect 4 layer.  
But this message comes up in JLC "Detected 2 layer board of 119.25x188.21mm(4.69x7.41 inches)."

is the v4.5 board 2 layer and v4 board 4 layer?

tia
chuck merja

**Comment by m-elias** [comment]
The Standard is 2 layer, the Micro is 4 layer

**Comment by chuckmerja** [comment]
thank you!
